services:
  freyja-chat-api:
    build: .
    container_name: freyja-chat-api
    restart: always
    env_file:
      - ../../infrastructure/.env
    networks:
      - aesir_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.freyja-api.rule=PathPrefix(`/freyja-chat/api`)"
      - "traefik.http.routers.freyja-api.entrypoints=web"
      - "traefik.http.services.freyja-api.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.freyja-api-strip.stripprefix.prefixes=/freyja-chat"
      - "traefik.http.routers.freyja-api.middlewares=freyja-api-strip"

networks:
  aesir_net:
    external: true
