package com.aesirlogic.freyjachat.service;

import com.aesirlogic.freyjachat.client.OpenAPIClient;
import com.aesirlogic.freyjachat.model.*;
import com.fasterxml.jackson.databind.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import java.time.Instant;
import java.util.*;

@Service
public class CardStrategyResearchService {
    private static final List<String> ROLES=List.of("PRIMARY","SPECIALIST","KEEP_ALIVE","REVIEW_FOR_CLOSURE");
    private static final List<String> CATEGORIES=List.of("GENERAL","GROCERIES","DINING","GAS","TRAVEL","TRANSIT","STREAMING","ONLINE_SHOPPING","DRUGSTORES","HOME_IMPROVEMENT","ENTERTAINMENT","UTILITIES");
    private final OpenAPIClient client; private final CardStrategyQuotaService quotas; private final ObjectMapper mapper; private final String model;
    public CardStrategyResearchService(OpenAPIClient client,CardStrategyQuotaService quotas,ObjectMapper mapper,@Value("${openai.card-strategy.model:gpt-5.6-luna}") String model){this.client=client;this.quotas=quotas;this.mapper=mapper;this.model=model;}
    public CardStrategyResearchResponse research(CardStrategyResearchRequest request){
        if(request==null||request.getCards()==null||request.getCards().isEmpty()) throw new IllegalArgumentException("at least one card is required");
        if(request.getCards().size()>12) throw new IllegalArgumentException("at most 12 cards may be researched together");
        for(var card:request.getCards()) if(card.getAccountId()==null||card.getAccountId().isBlank()||card.getName()==null||card.getName().isBlank()) throw new IllegalArgumentException("each card requires accountId and name");
        var quota=quotas.reserve(); JsonNode raw=client.getResponsesJson(body(request));
        try { JsonNode result=mapper.readTree(output(raw)); List<CardStrategyResearchResponse.CardAssessment> cards=new ArrayList<>();
            for(JsonNode card:result.path("cards")){List<CardStrategyResearchResponse.Benefit> benefits=new ArrayList<>();card.path("benefits").forEach(b->benefits.add(CardStrategyResearchResponse.Benefit.builder().category(b.path("category").asText()).reward(b.path("reward").asText()).conditions(b.path("conditions").asText()).build()));cards.add(CardStrategyResearchResponse.CardAssessment.builder().accountId(card.path("accountId").asText()).summary(card.path("summary").asText()).annualFee(card.path("annualFee").asText()).role(card.path("role").asText()).benefits(benefits).build());}
            List<CardStrategyResearchResponse.CategoryRecommendation> recs=new ArrayList<>();result.path("categoryRecommendations").forEach(r->recs.add(CardStrategyResearchResponse.CategoryRecommendation.builder().category(r.path("category").asText()).accountId(r.path("accountId").asText()).reward(r.path("reward").asText()).rationale(r.path("rationale").asText()).build()));
            return CardStrategyResearchResponse.builder().cards(cards).categoryRecommendations(recs).sources(sources(raw)).generatedAt(Instant.now()).usage(usage(raw)).quota(quota).build();
        }catch(Exception e){throw new IllegalStateException("OpenAI returned an unreadable card strategy",e);}
    }
    private Map<String,Object> body(CardStrategyResearchRequest request){StringBuilder input=new StringBuilder("Research current ongoing US benefits for this exact credit-card portfolio. Compare the cards and recommend the best owned card for each spending category. Ignore welcome bonuses. State caps, activation, membership, portal, and rotating-quarter conditions. Use only verified current benefits. Do not give financial advice or suggest opening cards. Cards:\n");request.getCards().forEach(c->input.append("- accountId=").append(c.getAccountId()).append(", name=").append(c.getName()).append(", institution=").append(Objects.toString(c.getInstitution(),"unknown")).append(", owner notes=").append(Objects.toString(c.getKnownBenefits(),"[]")).append('\n'));
        Map<String,Object> benefit=obj(Map.of("category",enm(CATEGORIES),"reward",str(),"conditions",str()),List.of("category","reward","conditions"));Map<String,Object> card=obj(Map.of("accountId",str(),"summary",str(),"annualFee",str(),"role",enm(ROLES),"benefits",arr(benefit,12)),List.of("accountId","summary","annualFee","role","benefits"));Map<String,Object> rec=obj(Map.of("category",enm(CATEGORIES),"accountId",str(),"reward",str(),"rationale",str()),List.of("category","accountId","reward","rationale"));Map<String,Object> schema=obj(Map.of("cards",arr(card,12),"categoryRecommendations",arr(rec,12)),List.of("cards","categoryRecommendations"));Map<String,Object> body=new LinkedHashMap<>();body.put("model",model);body.put("instructions","Return a concise source-grounded portfolio strategy. Preserve supplied accountId values exactly. Omit unverified benefits.");body.put("input",input.toString());body.put("tools",List.of(Map.of("type","web_search","search_context_size","low")));body.put("tool_choice","required");body.put("max_tool_calls",1);body.put("max_output_tokens",4000);body.put("reasoning",Map.of("effort","none"));body.put("include",List.of("web_search_call.action.sources"));body.put("store",false);body.put("text",Map.of("format",Map.of("type","json_schema","name","card_strategy","strict",true,"schema",schema)));return body;}
    private Map<String,Object> obj(Map<String,Object> p,List<String> r){return Map.of("type","object","additionalProperties",false,"properties",p,"required",r);}private Map<String,Object> str(){return Map.of("type","string");}private Map<String,Object> enm(List<String> v){return Map.of("type","string","enum",v);}private Map<String,Object> arr(Map<String,Object> i,int max){return Map.of("type","array","maxItems",max,"items",i);}
    private String output(JsonNode raw){for(JsonNode item:raw.path("output"))if("message".equals(item.path("type").asText()))for(JsonNode content:item.path("content"))if("output_text".equals(content.path("type").asText()))return content.path("text").asText();throw new IllegalStateException("OpenAI response contained no output text");}
    private List<CardStrategyResearchResponse.Source> sources(JsonNode raw){LinkedHashMap<String,String> found=new LinkedHashMap<>();for(JsonNode item:raw.path("output"))for(JsonNode source:item.path("action").path("sources")){String url=source.path("url").asText();if(url.startsWith("https://")||url.startsWith("http://"))found.putIfAbsent(url,source.path("title").asText(url));}return found.entrySet().stream().limit(8).map(e->CardStrategyResearchResponse.Source.builder().title(e.getValue()).url(e.getKey()).build()).toList();}
    private CardStrategyResearchResponse.Usage usage(JsonNode raw){JsonNode u=raw.path("usage");return CardStrategyResearchResponse.Usage.builder().inputTokens(u.path("input_tokens").asLong()).cachedInputTokens(u.path("input_tokens_details").path("cached_tokens").asLong()).outputTokens(u.path("output_tokens").asLong()).reasoningTokens(u.path("output_tokens_details").path("reasoning_tokens").asLong()).totalTokens(u.path("total_tokens").asLong()).build();}
}
